dist: bionic
language: ruby
services:
  - postgresql
  - rabbitmq
before_install:
  - sudo apt-get install libsodium23 -y
before_script:
  - cp config/database.yml.travis config/database.yml
  - bin/rake db:create
  - bin/rake db:migrate
