dist: bionic
language: ruby
services:
  - postgresql
  - rabbitmq
before_install:
  - sudo apt-get install libsodium23 -y
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn
before_script:
  - cp config/database.yml.travis config/database.yml
  - bin/rake db:create db:migrate RAILS_ENV=test
  - bin/rails webpacker:compile
cache:
  bundler: true
  directories:
    - node_modules
  yarn: true
