services:
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5439:5432"

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -p 3000 -b 0.0.0.0"
    environment: &app_env
      DATABASE_URL: postgres://postgres:password@db:5432/promise_authentication_development
      RAILS_ENV: development
      NODE_ENV: development
      RAILS_BIND: 0.0.0.0
    volumes: &app_volumes
      - .:/app
      - bundle_cache:/usr/local/bundle
      - node_modules:/app/node_modules
    ports:
      - "3003:3000"
    depends_on:
      - db

  js:
    build: .
    command: yarn build --watch
    environment: *app_env
    volumes: *app_volumes
    depends_on:
      - web

  css:
    build: .
    command: bash -c "bundle exec rails assets:precompile ; bundle exec rails tailwindcss:watch"
    environment: *app_env
    volumes: *app_volumes
    depends_on:
      - web

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres_data:
  bundle_cache:
  node_modules:
  rabbitmq_data:
