networks:
  promise-network:
    external: true

services:
  web:
    build: .
    command: bash -c "bundle exec rails db:prepare; rm -f tmp/pids/server.pid && bin/dev"
    stdin_open: true
    environment:
      PROMISE_KEY_REGISTRY_API_ROOT: http://promise_kms:3000/api/secret
      RAILS_ENV: development
      NODE_ENV: development
      RAILS_BIND: 0.0.0.0
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
      - node_modules:/app/node_modules
    ports:
      - "3003:3000"
    networks:
      - promise-network

volumes:
  postgres_data:
  bundle_cache:
  node_modules:
